<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-senti_robos.Host-f1e4c016-cea6-4f79-9614-48025493cc3e</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.EventGrid" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\senti_robos.ServiceDefaults\senti_robos.ServiceDefaults.csproj" />
    <ProjectReference Include="..\senti_robos.Application\senti_robos.Application.csproj" />
    <ProjectReference Include="..\senti_robos.Infrastructure\senti_robos.Infrastructure.csproj" />
  </ItemGroup>

</Project>
